version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: PST8PDT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: pm2
    versions:
    - 4.5.1
    - 4.5.4
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: "@types/pg"
    versions:
    - 7.14.7
    - 7.14.9
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: "@types/cors"
    versions:
    - 2.8.9
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.166
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/express"
    versions:
    - 4.17.9
  - dependency-name: "@emurgo/cardano-serialization-lib-nodejs"
    versions:
    - 4.3.0
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: "@types/config"
    versions:
    - 0.0.37
  - dependency-name: config
    versions:
    - 3.3.3
  rebase-strategy: disabled
