# This is a basic workflow to help you get started with Actions

name: Build-Push-Docker-onRelease

# Controls when the workflow will run
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, edited]
#   push:
#     tags:
#       - "v*.*.*"
#       - "pre-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dcspark/cardano-backend:${{ github.event.release.tag_name }}
          cache-from: type=registry,ref=dcspark/cardano-backend:${{ github.event.release.tag_name }}
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64

